### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"adrien.riez@hotmail.be",
  "password":"123*"
}
> {%
  client.global.set("adrienToken", response.body.token);
%}

###
POST {{baseUrl}}/objet/accepterObject/1
Authorization: {{adrienToken}}
###
GET http://localhost:3000/auths/user
Content-Type: application/json
Authorization:{{adrienToken}}

### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"jean.jacques@hotmail.be",
  "password":"123*"
}
> {%
  client.global.set("jeanJacques", response.body.token);
%}
### Register
POST http://localhost:3000/auths/register
Content-Type: application/json

{
  "email":"test17@hotmail.be",
  "password":"oui",
  "nom":"test2",
  "prenom":"test2",
  "gsm": "044444444"
}
> {%
  client.global.set("leonToken", response.body.token);
%}

### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"test17@hotmail.be",
  "password":"oui"
}
> {%
  client.global.set("memberToken", response.body.token);
%}



###
GET {{baseUrl}}/auths/user
Content-Type: application/json
Authorization:{{jeanJacques}}

###
GET  {{baseUrl}}/objet/typeObjet

###
GET  {{baseUrl}}/disponibilite

###
GET {{baseUrl}}/objet

###
GET {{baseUrl}}/objet
Authorization: {{adrienToken}}

###
GET {{baseUrl}}/objet/getPicture/0

###
GET {{baseUrl}}/users


###
GET {{baseUrl}}/users
Authorization: {{jeanJacques}}

###
GET {{baseUrl}}/users
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/4/confirmHelper

###
POST {{baseUrl}}/users/4/confirmHelper
Authorization: {{jeanJacques}}

###
POST {{baseUrl}}/users/4/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/7/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/1/confirmHelper
Authorization: {{adrienToken}}

###
PUT {{baseUrl}}/objet/vendreObject/3
Authorization: {{adrienToken}}
