### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"adrien.riez@hotmail.be",
  "password":"123*"
}
> {%
  client.global.set("adrienToken", response.body.token);
%}


###
GET http://localhost:3000/auths/user
Content-Type: application/json
Authorization:{{adrienToken}}

### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"jean.jacques@hotmail.be",
  "password":"123*"
}
> {%
  client.global.set("memberToken", response.body.token);
%}
### Register
POST http://localhost:3000/auths/register
Content-Type: application/json

{
  "email":"testé8@hotmail.be",
  "password":"oui",
  "nom":"test2",
  "prenom":"test2",
  "gsm": "044444444"
}
> {%
  client.global.set("leonToken", response.body.token);
%}

### Login with default user credentials
POST http://localhost:3000/auths/login
Content-Type: application/json

{
  "email":"steven.agbassah@student.vinci.be",
  "password":"123*"
}
> {%
  client.global.set("aidantToken", response.body.token);
%}



###
GET {{baseUrl}}/auths/user
Content-Type: application/json
Authorization:{{memberToken}}

###
GET  {{baseUrl}}/objet/typeObjet

###
GET  {{baseUrl}}/disponibilite

###
GET {{baseUrl}}/disponibilite

###
GET {{baseUrl}}/objet/storeObject

###
GET {{baseUrl}}/objet
Authorization: {{adrienToken}}

###
GET {{baseUrl}}/objet/getPicture/0

###
GET {{baseUrl}}/users


###
GET {{baseUrl}}/users
Authorization: {{jeanJacques}}

###
GET {{baseUrl}}/users
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/4/confirmHelper

###
POST {{baseUrl}}/users/4/confirmHelper
Authorization: {{jeanJacques}}

###
POST {{baseUrl}}/users/3/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/4/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/7/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/users/1/confirmHelper
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/objet/refuserObject/7
Authorization: {{adrienToken}}
Content-Type: application/json

{
  "message": "refus"
}

###
POST {{baseUrl}}/objet/accepterObject/8
Authorization: {{adrienToken}}

###
POST {{baseUrl}}/objet/depositObject/8
Authorization: {{aidantToken}}
Content-Type: application/json

{
  "localisation" : "Magasin"
}

###
POST {{baseUrl}}/objet/misEnVenteObject/8
Authorization: {{aidantToken}}
Content-Type: application/json

{
  "prix" : "5"
}

###
POST {{baseUrl}}/objet/vendreObject/8
Authorization: {{aidantToken}}

###
GET {{baseUrl}}/auths/getPicture/14
Authorization: {{adrienToken}}


###
GET {{baseUrl}}/users/1
Authorization: {{aidantToken}}

###
POST {{baseUrl}}/disponibilite
Content-Type: application/json

{
  "date": "2023-04-29",
  "plage": "apres midi"
}

###
POST {{baseUrl}}/objet/ajouterObjet
Content-Type: application/json

{
  "description": "de",
  "photo": "d"
}

###
PUT {{baseUrl}}/objet/updateObject/4
Content-Type: application/json

{
  "description" : "1",
  "version" : "9"

}

###
PUT {{baseUrl}}/users/2
Authorization: {{memberToken}}
Content-Type: application/json

{
  "nom": "Lebron",
  "prenom": "James",
  "email": "lebron.james@nba.be",
  "gsm": "019849784-474"
}


###
PUT {{baseUrl}}/users/2
Authorization: {{memberToken}}
Content-Type: application/json

{
  "nom": "Lebron",
  "prenom": "James",
  "email": "lebron.james@nba.be",
  "gsm": "            ",
  "image" : "efzerkogj"
}